### ISSUE TITLE
报错通知过多

### ISSUE THREAD

**Issue by JamYiz** [skykeyjoker/A-SOUL-Notification#9]
一天之中大概能出现30+的报错通知，大佬是否能够解决一下，感觉有点频繁了。
而且感觉30s可以适当延长。

**Comment by skykeyjoker** [comment]
感谢的使用与反馈。
报错通知过多的问题我也一直在想办法，后面应该会有改进:P。这个不光跟叔叔的限制有关系，还跟使用者的网络环境有关。
30s已经是延长过的结果了，一直到上个版本查询频率都是5s。这次选用30s也是借鉴了另外一个运行在vsc上的脚本。
我目前有一个不太成熟的计划，我可能会关掉所有的非致命错误的通知，将致命错误的应对措施改为延时等待而不是直接退出程序。

**Comment by JamYiz** [comment]
> 感谢使用与反馈。 报错通知过多的问题我也一直在想办法，后面应该会有改进:P。这个不光跟叔叔的限制有关系，还跟使用者的网络环境有关。 30s已经是延长过的结果了，一直到上个版本查询频率都是5s。这次选用30s也是借鉴了另外一个运行在vsc上的脚本。 我目前有一个不太成熟的计划，我可能会关掉所有的非致命错误的通知，将致命错误的应对措施改为延时等待而不是直接退出程序。

感觉这个思路很不错，因为即便报错好像作为使用者也没有办法干预，只能干着急😂😂。而且可以在运行的时候发个通知提醒，这样就不用在任务管理器查看确认了。

**Comment by skykeyjoker** [comment]
已发布新版本
